### PR TITLE
Update test version of ORT dists for Segment Anything including opSupportLimits

### PR DESCRIPTION
**Pull request by ibelem**
Update test version of ORT dists which added opSupportLimits() feature.

Currently only Segment Anything demo is using test version of ORT dists, other demos are using public dev versions.

@fdwr PTAL

CC @Honry

### CODE REVIEW

**Comment by fdwr** [comment]
Btw, ONNX 1.17.0 was just published, which includes EinSum :). https://github.com/onnx/onnx/releases/tag/v1.17.0

**Comment by fdwr** [comment]
@ibelem : Do you know an easy way to know what the "Test version" of ORT here was? I *think* it was a custom build (maybe with EinSum support) and may not map to any specific public build.

**Comment by ibelem** [comment]
> @ibelem : Do you know an easy way to know what the "Test version" of ORT here was? I _think_ it was a custom build (maybe with EinSum support) and may not map to any specific public build.

Correct, they were built by @Honry which include landed/not landed PRs (before next dev builds) to fix urgent demo issues, and EinSum support that not included public dev builds. Shall we rename it or something else I can do? @fdwr

**Comment by fdwr** [comment]
Well, I just wondered if there might be an easy way looking into the dist/ folder to tell (some projects have a little version text file in them or a version string somewhere in the code near the top). Alternately if we just include the ORT base commit or nearest approximate number in the CR description, that could help too. TY. (context: a coworker was trying to narrow down a bug and wondered the matching version of the test version)

**Pull request merged**
